### ISSUE TITLE
Initial dataset upload Class labels

### ISSUE THREAD

**Issue by miguelehernandez** [EpistasisLab/Aliro#442]
When uploading initial datasets to the data directory for Classification, we must handle class labels in the metadata.json file.

**Comment by jay-m-dev** [comment]
This issue was opened due to a discussion of allowing users to edit the class labels on the GUI while in the process of uploading the dataset. We discussed that if we implement this we may need to update how this is handled during initial dataset uploads (_metadata.json file)
We went a different route and implemented GPT which now allows for datasets to be modified and re-uploaded. Therefore, there's no longer a need to work on this issue.
